/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fish.gltf 
Author: rkuhlf (https://sketchfab.com/rkuhlf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fish-5a2b7976ef5c44658de22e98bf381277
Title: Fish
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Fish(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/fish/fish.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions.FishSwimming) {
      actions.FishSwimming.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="BrownFishArmature_13"
                position={[-2.071, 4.396, 0.755]}
                rotation={[-1.175, -0.652, -0.906]}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="BrownFish_12" />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.BrownFish}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.RedPart}
                    skeleton={nodes.Object_8.skeleton}
                  />
                </group>
              </group>
              <group
                name="ClownFishArmature_23"
                position={[-0.06, 1.876, 0.925]}
                rotation={[0.194, -0.464, 0.083]}
              >
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="ClownFish_22" />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.ClownFishOrange}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_26"
                    geometry={nodes.Object_26.geometry}
                    material={materials.ClownFishWhite}
                    skeleton={nodes.Object_26.skeleton}
                  />
                  <skinnedMesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    material={materials.ClownFishBlack}
                    skeleton={nodes.Object_27.skeleton}
                  />
                </group>
              </group>
              <group
                name="TunaArmature_33"
                position={[-1.953, 3.909, -2.514]}
                rotation={[-3.064, -0.671, -2.528]}
              >
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <group name="Tuna_32" />
                  <skinnedMesh
                    name="Object_40"
                    geometry={nodes.Object_40.geometry}
                    material={materials.Fish}
                    skeleton={nodes.Object_40.skeleton}
                  />
                  <skinnedMesh
                    name="Object_41"
                    geometry={nodes.Object_41.geometry}
                    material={materials.FishUnderside}
                    skeleton={nodes.Object_41.skeleton}
                  />
                </group>
              </group>
              <group
                name="DoryArmature_47"
                position={[-2.523, 2.693, 3.813]}
                rotation={[0.697, 0.18, 0.206]}
              >
                <group name="GLTF_created_3">
                  <primitive object={nodes.GLTF_created_3_rootJoint} />
                  <group name="Plane_46" />
                  <skinnedMesh
                    name="Object_54"
                    geometry={nodes.Object_54.geometry}
                    material={materials.DoryBlue}
                    skeleton={nodes.Object_54.skeleton}
                  />
                  <skinnedMesh
                    name="Object_55"
                    geometry={nodes.Object_55.geometry}
                    material={materials.DoryYellow}
                    skeleton={nodes.Object_55.skeleton}
                  />
                  <skinnedMesh
                    name="Object_56"
                    geometry={nodes.Object_56.geometry}
                    material={materials.DoryBlack}
                    skeleton={nodes.Object_56.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/fish/fish.gltf");
