/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 aq.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Aq(props) {
  const { nodes, materials } = useGLTF("/aquarium_v4/aq.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Algae1_Algae_2_0.geometry}
        material={materials.Algae_2}
        position={[0, 5.038, -39.665]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Algae2_Algae_1_0.geometry}
        material={materials.Algae_1}
        position={[-6.54, -18.944, 168.612]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={93.455}
      />
      <mesh
        geometry={nodes.Aquarium_Aquarium_0.geometry}
        material={materials.Aquarium}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Dirt_Dirt_0.geometry}
        material={materials.Dirt}
        position={[0, -89.344, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[98.745, 100, 100]}
      />
      <mesh
        geometry={nodes.Root_Root_0.geometry}
        material={materials.Root}
        position={[-10.615, -71.429, -114.205]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/aquarium_v4/aq.gltf");
